#!/bin/bash
used=$(free -h | awk '/Mem:/ {print $3}')
total=$(free -h | awk '/Mem:/ {print $2}')
pct=$(free | awk '/Mem:/ {printf "%.0f", $3/$2 * 100}')
echo "{\"text\":\"󰍛 $used\",\"tooltip\":\"RAM: $used / $total ($pct%)\",\"class\":\"memory\"}"
