windowrule = no_screen_share on, match:workspace s[true]

xwayland {
    force_zero_scaling = true
}

# windowrule = border_color rgb(aa0000), match:class ^(?i).*bitwig.*
# windowrule = border_color rgb(aa0000), match:class ^(?i).*bitwig.*
