bind=SUPER, E ,submap, noalt

submap=noalt

    ubind = ALT, 1 
    ubind = ALT, 2 
    ubind = ALT, 3 
    ubind = ALT, 4 
    ubind = ALT, 5 
    ubind = ALT, 6 
    ubind = ALT, 7 
    ubind = ALT, 8 
    ubind = ALT, 9 
    ubind = ALT, 0 
    ubind = ALT SHIFT, 1
    ubind = ALT SHIFT, 2
    ubind = ALT SHIFT, 3
    ubind = ALT SHIFT, 4
    ubind = ALT SHIFT, 5
    ubind = ALT SHIFT, 6
    ubind = ALT SHIFT, 7
    ubind = ALT SHIFT, 8
    ubind = ALT SHIFT, 9
    ubind = ALT SHIFT, 0

    bind= SHIFT , escape , submap, reset

submap=reset

# bind=SUPER CTRL, F, submap, fr
#
# submap=fr
#
#     input {
#         kb_layout = us,fr
#         kb_options = caps:escape,grp:alts_toggle
#     }
#
#     bind= SHIFT , escape , submap, reset
#
# submap=reset
